version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 1ncrease
      MYSQL_DATABASE: autofixer
      MYSQL_USER: autofixer
      MYSQL_PASSWORD: Autofixer@2022
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: control
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1ncrease

