version: '3.8'

services:
  # Next.js app
  web:
    image: node:18
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "1213:3000"
    environment:
      - NODE_ENV=development
    command: >
      bash -c "npm install && npx prisma db push && PORT=3000 npm run dev"
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/var/backup
    ports:
      - "6433:5432"

  # Ssl & routing app - caddy
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile    # Mount your Caddyfile
      - caddy_data:/data                    # SSL certificates, etc.
      - caddy_config:/config
    # networks:
    #   - caddy_network
    restart: unless-stopped

 # pgAdmin
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test@test.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "5051:80"
  #   depends_on:
  #     - postgres

volumes:
  postgres-data:
    driver: local
  caddy_data:
  caddy_config: